### ISSUE TITLE
Question: supporting non-continuous Mat ?

### ISSUE THREAD

**Issue by brianm-sra** [pthom/cvnp#1]
I tried copying some of your code to my project.

When I ran my Python program, I got the error

ValueError: Only continuous Mats supported.

from the method mat_to_nparray(const cv::Mat& m

where it checks if (!m.isContinuous())

What is needed to be modified to support non-continuous Mats ?

**Comment by pthom** [comment]
Suggestion: replace your non continuous matrix `m` by  `m_continuous = m.clone();`

`m_continuous` should then be a continuous copy.
