### ISSUE TITLE
shall the array copy when without share_memory?

### ISSUE THREAD

**Issue by ShiyangZhang** [pthom/cvnp#10]
when shared memory  not used , it seems that 
m is out of scope, it is thus `m.data` freed, and the returned array directly points to the old address on the stack!`:
https://github.com/pthom/cvnp/blob/602aa26a48eae4255a47787e6b2b7f423f2cd31f/cvnp/cvnp.cpp#L91

```
pybind11::array make_array()
{
    cv::Mat m(cv::Size(10, 10), CV_8UC1);               // create a matrix on the stack
    pybind11::array a = cvnp::mat_to_nparray(m, false); 
    return a;                                                        
}  // Here be dragons, when closing the scope!
   // m is now out of scope, it is thus freed, 
   // and the returned array directly points to the old address on the stack!
```

**Comment by ShiyangZhang** [comment]
> Hi,
> 
> I'm not sure I understand your question. I you call cvnp::mat_to_nparray(m, false), then m and m.data should be copied, and it should not matter that m was previously on the stack.

Thank you for your explanation. I got it.

By the way, If I understand correctly, when shared memory is used, the `py::capsule` will hold a reference to the original `cv::Mat`( cv::Mat itself act as  a smart pointer) . https://github.com/pthom/cvnp/blob/602aa26a48eae4255a47787e6b2b7f423f2cd31f/cvnp/cvnp.cpp#L69
and so will keep the stack data alive even if the function returned. Did I misunderstand something?

**Comment by pthom** [comment]
You might be right
I will need to study this more in details

**Comment by pthom** [comment]
Hi,

Thanks for your remarks. 
You were right about the fact the the py::capsule does indeed keep the C++ matrix alive. 
I had to do some adaptations for this to work, and this introduced breaking changes in the API, but they are beneficial IMHO.

I updated the code, and now:

* `cv::Mat`: standard OpenCV matrices are always transformed to numpy array *with shared memory*
  (i.e. modification to matrices elements made from python are immediately visible to C++, and vice-versa).
* Sub-matrices:
  * Sub-matrices created from C++ can also be shared to python
  * Sub-matrices created from python will need to be transformed to a contiguous array before being shared to C++
* `cv::Matx`: small matrices are transformed to numpy arrays *without shared memory*
* Casts *without* shared memory for simple types, between `cv::Size`, `cv::Point`, `cv::Point3` and python `tuple`

(The previous API, it is still available in the [original_api](https://github.com/pthom/cvnp/tree/original_api) branch.)

**Comment by ShiyangZhang** [comment]
> Hi,
> 
> Thanks for your remarks. You were right about the fact the the py::capsule does indeed keep the C++ matrix alive. I had to do some adaptations for this to work, and this introduced breaking changes in the API, but they are beneficial IMHO.
> 
> I updated the code, and now:
> 
> * `cv::Mat`: standard OpenCV matrices are always transformed to numpy array _with shared memory_
>   (i.e. modification to matrices elements made from python are immediately visible to C++, and vice-versa).
> * Sub-matrices:
>   
>   * Sub-matrices created from C++ can also be shared to python
>   * Sub-matrices created from python will need to be transformed to a contiguous array before being shared to C++
> * `cv::Matx`: small matrices are transformed to numpy arrays _without shared memory_
> * Casts _without_ shared memory for simple types, between `cv::Size`, `cv::Point`, `cv::Point3` and python `tuple`
> 
> (The previous API, it is still available in the [original_api](https://github.com/pthom/cvnp/tree/original_api) branch.)

Awesome!
