### ISSUE TITLE
Numpy 2 compatibility

### ISSUE THREAD

**Issue by virtuald** [pthom/cvnp#17]
Just FYI, I've had two users report that the "Only contiguous numpy arrays are supported" check fails when they have numpy 2.x installed with bindings that were compiled with pybind 2.11. I haven't looked into it yet.

Reference:

* https://github.com/robotpy/mostrobotpy/issues/99
* https://www.chiefdelphi.com/t/robotpy-opencv-raspberry-pi-help/470001

**Comment by pthom** [comment]
﻿Hello Dustin,

Thanks for reporting. I could reproduce and fix the issue. 
There was also another small issue with small matrices (cv::Matx) when using numpy2. It is fixed also.
